export const SECRET_ACTIONS = [
  "Regarde-moi et dis-moi exactement ce que tu veux me faire, sans détour",
  "Approche-toi et fais durer le moment avant de m’embrasser",
  "Dis-moi ce que tu penses de moi quand t’as vraiment envie",
  "Rapproche-toi et murmure-moi quelque chose d’interdit",
  "Laisse-moi voir dans tes yeux que tu me veux",
  "Dis-moi ce que tu ferais si on était seuls sans limites",
  "Prends-moi contre toi avec intention",
  "Approche-toi et fais monter la tension sans parler",
  "Dis-moi ce qui te rend fou/folle chez moi",
  "Bloque-moi doucement et regarde-moi intensément",
  "Dis-moi ce que tu veux que je fasse là maintenant",
  "Fais durer un moment proche sans aller jusqu’au bout",
  "Dis-moi ce que tu ressens physiquement en ce moment",
  "Approche-toi et laisse le silence faire le reste",
  "Regarde-moi et fais-moi comprendre ton envie sans parler",
  "Dis-moi un truc que tu n’oserais jamais dire à voix haute normalement",
  "Laisse-moi sentir que tu perds un peu le contrôle",
  "Dis-moi ce que tu veux me faire en premier",
  "Rapproche-toi très lentement jusqu’à ce que ça devienne intense",
  "Dis-moi ce que tu imagines quand tu penses à moi",
  "Approche-toi et joue avec la distance",
  "Dis-moi un truc que tu trouves vraiment attirant chez moi",
  "Fais-moi comprendre que tu me désires sans dire “je te veux”",
  "Dis-moi ce que tu ferais si je te laissais faire ce que tu veux",
  "Approche-toi et fais durer le moment au maximum",
  "Dis-moi ce que tu veux que je te fasse",
  "Laisse-moi sentir que tu hésites… puis fais-le",
  "Regarde-moi comme si on était seuls au monde",
  "Dis-moi une envie que t’as jamais dite",
  "Approche-toi et fais monter la tension jusqu’au bout",
] as const;

export const SECRET_TRUTHS = [
  "À quel moment t’as le plus envie de moi ?",
  "Qu’est-ce qui t’excite le plus chez moi ?",
  "Qu’est-ce que tu imagines quand tu penses à moi ?",
  "Ce que tu veux vraiment faire avec moi mais que tu retiens",
  "Ce que tu ressens quand je suis très proche",
  "Ce que tu regardes en premier quand tu me désires",
  "Une pensée que tu as déjà eue sur moi mais jamais dite",
  "Ce que tu veux que je comprenne sans que tu le dises",
  "Le moment où tu as le plus perdu le contrôle avec moi",
  "Ce qui te fait craquer immédiatement chez moi",
  "Ce que tu veux que je fasse différemment",
  "Ce que tu aimes quand je prends l’initiative",
  "Une envie que tu n’as jamais exprimée",
  "Ce que tu trouves le plus attirant dans notre relation",
  "Ce que tu veux ressentir avec moi",
  "Une chose que tu veux essayer avec moi",
  "Ce que tu penses quand je te regarde intensément",
  "Ce que tu veux que je devine sur toi",
  "Ce que tu ressens quand on est collés",
  "Une chose que tu voudrais que je fasse plus souvent",
  "Ce que tu trouves irrésistible chez moi",
  "Ce que tu veux que je te dise dans ces moments-là",
  "Une envie que tu gardes pour toi",
  "Ce que tu ressens quand tu me touches",
  "Ce que tu veux que je comprenne sans mots",
  "Ce qui te fait monter en tension avec moi",
  "Une chose que tu veux vivre intensément avec moi",
  "Ce que tu penses vraiment quand tu es avec moi",
  "Une limite que tu aimerais dépasser avec moi",
  "Ce que tu veux que je ressente avec toi",
] as const;

export type SecretCardKind = "action" | "truth";

export type SecretCard = {
  kind: SecretCardKind;
  prompt: string;
};
